version: "3"
services:
  dns_storage:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      DATABASE_HOSTNAME: database
    volumes:
      - .:/app
  database:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-volume:
